# Generated by Django 4.1.3 on 2022-11-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questions_cat_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='Q_Id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='U_ID',
        ),
        migrations.AddField(
            model_name='questions',
            name='u_email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
