# Generated by Django 4.1.2 on 2022-11-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_rename_q_id_questions_id_remove_questions_u_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='cat_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
