# Generated by Django 4.1.3 on 2022-11-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_questions_cat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
