# Generated by Django 3.2.15 on 2022-10-16 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('A_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Q_answer', models.CharField(max_length=30)),
                ('dislike', models.IntegerField()),
                ('like', models.IntegerField()),
                ('Q_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questions')),
                ('U_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ouruser')),
            ],
        ),
    ]
