# Generated by Django 4.1.3 on 2022-11-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='A_Id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='U_ID',
        ),
        migrations.AddField(
            model_name='answer',
            name='u_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='Q_ID',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
