# Generated by Django 4.1.3 on 2022-11-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ouruser_img_ouruser_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ouruser',
            old_name='U_Id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='Bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='Num_of_followers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='Num_of_following',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='password',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
