# Generated by Django 4.1.4 on 2022-12-06 12:26

from django.db import migrations
import encrypt_decrypt_fields.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_u_id_ouruser_id_alter_ouruser_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouruser',
            name='password',
            field=encrypt_decrypt_fields.django_fields.EncryptedBinaryField(blank=True, null=True),
        ),
    ]
