# Generated by Django 4.1.4 on 2022-12-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_ouruser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouruser',
            name='password',
            field=models.TextField(null=True),
        ),
    ]
