# Generated by Django 4.1.2 on 2022-11-15 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_id',
            new_name='id',
        ),
    ]
